version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: admin_panel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - admin-network

  # Aplicación NestJS
  backend:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: admin_panel_db
      JWT_SECRET: tu-jwt-secret-super-secreto-y-largo
      JWT_EXPIRES_IN: 24h
      CORS_ORIGIN: http://localhost:4200
      SWAGGER_TITLE: Admin Panel API
      SWAGGER_DESCRIPTION: API REST para sistema de gestión comercial
      SWAGGER_VERSION: 1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - admin-network

volumes:
  postgres_data:

networks:
  admin-network:
    driver: bridge
